### ISSUE TITLE
Conversion vers ChordPro

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patadata#22]
J'ai du mal à voir l'état d'avancement pour la transition vers le format chrodpro (#19 est particulièrement longue).
Du coup voici une méta-issue pour regrouper tous les sujets qui s'y rapportent (et éviter des issues très longues où plusieurs sujets se retrouvent mélangés).

Je vais en profiter pour faire une nouvelle branche [progressive_conversion](https://github.com/patacrep/patadata/tree/progressive_conversion)(propre si possible), dans laquel chacun des points suivant sera une sous-branche

- [x] Correction des inconsistances évidentes dans les chants LaTeX (voir #26)
- [x] `echo` sur plusieurs lignes (voir #23)
- [ ] `rep` imbriqué dans `echo` (voir #24)
- [ ] `meter` en milieu de chant (voir #25)
- [ ] `&` ou `b` dans les accords (voir #27)
- ...
- [ ] Conversion finale (et création des fichiers avec la [bonne extension](https://github.com/patacrep/patacrep/issues/114))

Je garderai probablement en parallèle une branche `convert_wip`, que je rebaserai sur les dernières modifs et auxquelles j'appliquerai mon script de conversion.

**Comment by oliverpool** [comment]
Avec l'abandon de #18, cette issue n'a plus d'intérêt
